FROM python:3-slim-bookworm

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

RUN apt-get update && apt-get install -y procps curl

COPY ./requirements.txt /app/requirements.txt
COPY ./packages/inspector_mv-0.0.3.tar.gz /app/packages/inspector_mv-0.0.3.tar.gz

RUN pip install --upgrade pip && pip install -r requirements.txt

COPY . /app/

CMD ["flask", "run"]
