FROM python:3-slim-buster

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app
RUN pip install --upgrade pip
COPY ./requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

COPY . /app/

ENTRYPOINT ["python3", "/app/__init__.py", "-p", "5000", "-n", "-s"]

CMD ["/mnt/llc/llc_data/clams"]
